name: form_validate
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  hive: ^2.2.3
  http: ^1.5.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  cupertino_icons: ^1.0.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
